version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_service
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:latest
    container_name: mysql_service
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  task_insert:
    build: ../task-insert-service/
    command: sh -c "sleep 10 && uvicorn task_insert_app:app --host 0.0.0.0 --port 8000 --reload"
    container_name: task_insert
    ports:
      - 8000:8000
    depends_on:
      - mysql

  task_schedular:
    build: ../schedular/ 
    command: sh -c "sleep 10 && python schedular.py"
    container_name: task_schedular
    depends_on:
      - mysql
      - redis



  dlq_processor:
    build: ../dlq-process/ 
    command: sh -c "sleep 10 && python dlq_processor.py"
    container_name: dlq_processor 
    depends_on:
      - mysql
      - redis





volumes:
  redis_data:
  mysql_data:
